### ISSUE TITLE
You broke my machine!

### ISSUE THREAD

**Issue by VladimirMilenko** [ahmedelgabri/dotfiles#15]
- check for prezto, OMZ, etc... since you depend on Zim
- prompt doesn't work when you run `make`
- maybe add a warning that it was only tested on a clean install
- `vimEnter` `autocmd` to install plug installs it in the wrong directoy
- maybe remove appStore apps from `Brewfile`?
- check for apps required to run `mx-init` & `mx`
- change `$GITHUB_USER` in `.zprofile` & your git info in `.gitconfig`
- launchagent has your paths & username

**Comment by ahmedelgabri** [comment]
- ~[-] check for prezto, OMZ, etc... since you depend on Zim~ Added a noted in `README`
- [x] prompt doesn't work when you run `make`
- [-] maybe add a warning that it was only tested on a clean install (not worth it, this was not created to work for anyone other than me)
- [x] `vimEnter` `autocmd` to install plug installs it in the wrong directoy
- ~[-] maybe remove appStore apps from `Brewfile`?~ _they are commented out already_
- [ ] check for apps required to run `mx-init` & `mx`
- [-] change `$GITHUB_USER` in `.zprofile` & your git info in `.gitconfig` fixed, you will need `~/.gitconfig.local` & `~/.zshrc.local` files to setup these.
- ~[-] launchagent has your paths & username~ (not worth it, this was not created to work for anyone other than me)

**Comment by ahmedelgabri** [comment]
It might be also a good idea to fork it, so you make changes you want & keep them
